### PR TITLE
Feature/453 mtls csrs

### LINKED ISSUE #453: mTLS CSRs
The mTLS implementation that we have works well, but I think I made some mistakes in understanding the required functionality. I have spelled out the diferences by annotating some notes below:

In these annotated notes:
 - Black is the "normal" mTLS behaviour
 - Blue is the behaviour currently implemented
 - Orange is where our implementation differs from our users' expectation

image
image

To match our users' expectations then, I think we need to do three things (in my estimated order of difficulty):

## ~1. Separate "frontend" and "testing" routes in nginx~
~We have three situations:~
 - ~"Frontend" routes, which should be served over HTTPS using LetsEncrypt certificates in production (or self-signed localhost certificates in development)~
 - ~"/testing-insecure" routes, which shouold be served over unencrypted HTTP~
 - ~"/testing" routes, which should be served using an encrypted mTLS connection.~

~I might be wrong, but I think right now the HTTPS for frontend and the mTLS routes use the same server block, which might make it difficult for us to use different server certificates in the two cases. In the "/testing" path, we will want to start using our own server key, self-signed by RootCA (see below).~

## 2. Generate client keys ourselves

In the form where users currently can upload a private key, cert and CA cert, it would be more secure for us to generate our own private key (otherwise someone else has a copy of our server key). The way I imagine this working is that we have a button to "create new key". When the user clicks it, we create a new key and a CSR inside the certificates table. The CSR is given to the user to download, and the user can then upload a signed certificate which we add to the certificates table. When we make a request to the SUT, we use the key that we generated, and the certificate that they uploaded. Note that it might take the user some time (maybe days) to generate the certificate, so it should be possible to have a "partially complete" certificate set without the client cert, and the user can return later to add it. If the user runs the test case before uploading the cert, then the request will fail and that's okay (it would be good if we can return a custom error saying "No client certificate has been uploaded").

## 3. Provide an interface for ITP to sign CSRs
Currently, we get SUTs to self-sign their client certificates. It would be more secure if we signed the certificates, so we need to provide some kind of interface for users to upload a CSR. ITP should then return a certificate signed by RootCA, which the user can install inside their SUT. Nginx will then receive requests from the SUT accompanied by this certificate, which we can validate using RootCA.

This does not need to be attached to a session, and the results do not need to be stored anywhere so I think the function can be stateless.

I _think_ this means that we don't need the script that regenerates ClientCA anymore.

I am very unsure if I have understood everything correctly, so I would appreciate any feedback if you think I have got anything wrong (or indeed if you think I've got it right, I would appreciate a 👍!)

### PR DESCRIPTION
**Pull request by jc-skushnir**
#453

### CODE REVIEW

**Comment by cjol** [comment]
Hi @jc-skushnir, I'm having trouble getting this to work. To test, I am using this simple test case:
```yaml
name: mTLS Demo
slug: mtls-demo
use_case: Demo
behavior: positive
description: Client wants to check it can make an mTLS connection to Server
  
components:
  - name: Client
    slug: client
  - name: Server
    slug: server
test_steps:
  - path: /mtls
    pattern: ^mtls$
    method: GET
    source: client
    target: server
    mtls: true
    request:
      method: GET
      uri: /mtls
      headers:
        accept: application/json
        content-type: application/json
    response:
      status: 200
      headers:
        x-date: '{{ new_date_iso8601() }}'
        content-type: application/json
```

As a quick tool to simulate a real mTLS server, I have used [this docker image](https://github.com/andreburgaud/docker-cert-auth) to test mTLS, following the steps below:

1. Set up a working directory

    ```bash
    mkdir mtls-test
    cd mtls-test
    ```

2. Create CA and server certificates.

    ```bash
    mkdir certs
    openssl genrsa -out certs/ca.key 4096
    openssl req -new -x509 -days 365 -key certs/ca.key -out certs/ca.crt \
    	   -subj "/C=GB/ST=England/L=London/O=GSMA/OU=ITL/CN=gsmainclusivetechlab.io/emailAddress=clittle@gsma.com"

    openssl genrsa -out certs/server.key 2048
    openssl req -new -key certs/server.key -out certs/server.csr \
    	   -subj "/C=GB/ST=England/L=London/O=GSMA/OU=ITL/CN=localhost/emailAddress=clittle@gsma.com"
    openssl x509 -req -days 365 -in certs/server.csr -out certs/server.crt \
    	   -CA certs/ca.crt -CAkey certs/ca.key -CAcreateserial
    ```

3. Run the demo server:

    ```bash
    docker run --rm -p 8443:443 -v`pwd`/certs:/etc/nginx/certs/ andreburgaud/nginx-cert-auth
    ```

4. Create a test session using the above test case, selecting `Server` as the only SUT and entering `https://localhost:8443` as the URL.

4. Select "Use Encryption", and download and sign the client CSR from ITP (saved as `certs/itp-client.csr`)

    ```bash
    openssl x509 -req -days 365 -in certs/itp-client.csr -out certs/itp-client.crt \
    	   -CA certs/ca.crt -CAkey certs/ca.key -CAcreateserial
    ```

5. Upload `certs/ca.crt` as the CA certificate, and `certs/itp-client.crt` as the client certificate, and complete the session creation wizard.
6. Run the test case, and I get the following error:

```
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://localhost:8443/mtls
```

Note that if I create a key and CSR myself manually, and connect to the test server using these credentials via curl, I have no problems:

```bash
❯ openssl genrsa -out certs/curl-client.key 2048
❯ openssl req -new -key certs/curl-client.key -out certs/curl-client.csr \
	   -subj "/C=GB/ST=England/L=London/O=GSMA/OU=ITL/CN=localhost/emailAddress=clittle@gsma.com"
❯ openssl x509 -req -days 365 -in certs/curl-client.csr -out certs/curl-client.crt \
	   -CA certs/ca.crt -CAkey certs/ca.key -CAcreateserial

❯ curl https://localhost:8443/mtls --cacert certs/ca.crt --cert certs/curl-client.crt --key certs/curl-client.key -i
HTTP/1.1 200 OK
Server: nginx/1.12.2
Date: Thu, 08 Apr 2021 10:18:44 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 82
Connection: keep-alive

emailAddress=clittle@gsma.com,CN=localhost,OU=ITL,O=GSMA,L=London,ST=England,C=GB

```

Do you get different results? I haven't yet reviewed the code to figure out where the problem is.

**Comment by jc-skushnir** [comment]
Hi @cjol,
coul you please check:

1. is CSR and private key matches by runing comands

> `openssl req -noout -modulus -in client.csr | openssl md5`  - downloaded CSR
> `openssl rsa -noout -modulus -in client.key | openssl md5` - key (you can find it inside docker container `docker-compose exec app sh` with path /etc/nginx/ssl/default-certs/client.key)

2. and make sure that `demo server` using same CA as uploaded `certs/ca.crt`

**Comment by cjol** [comment]
Hi @jc-skushnir  and @agalaguz sorry for the delay on getting back to you. I've just tried to repeat the steps above, and get the same results.

https://user-images.githubusercontent.com/1517675/115747663-63804900-a38d-11eb-9b2d-78bd292ff736.mp4

I am going to try to dive into the code and see what's going wrong. My guess is that there's something wrong with the way the CA cert is being used.

**Comment by cjol** [comment]
I'm about to log off for the day, but just a quick note - I think I'm being stupid, and this problem is to do with docker networking (i.e. the app container cannot communicate with my server through `localhost`). I will double check in the morning.

**Review by cjol — APPROVED** [review]
There are some small changes that I would like to make, but this is currently functional so I will merge this for now. Thank you!

**Comment by cjol** [comment]
I have

**Pull request merged**
