### PR TITLE
Feature/485 additional admin logs

### LINKED ISSUE #485: Display Additional Admin Logs
Currently, the admin has access to two types of log: audit log and Message Log. These should be unified under one "logging" screen, and some new logs should also be added. 

The new logging screen should default to the message log, and the other logs should be accessible through a sidebar. 

All three new logs are simply replicating files which are present in the application container, so that it is more convenient to view them without manually SSHing into the machine. The new logs which should be displayed are:

- NGINX Access Log -> `/var/log/nginx/access.log`
- NGINX Error Log -> `/var/log/nginx/error.log`
- Application Log -> `/var/www/html/storage/logs/laravel.log`
- Queue Log -> `/var/www/html/storage/logs/laravel.log` (inside the `queue` container, which will need to be mapped into the app container via docker volumes for display in the app)

In all three cases, the log files will potentially be very large. To avoid crashing the browser, one page should only display a maximum of the last 500 lines of the log. As a stretch goal, additional lines could be displayed through pagination, but it is acceptable to simply ignore anything before the last 500 lines.

### PR DESCRIPTION
**Pull request by yvoitenko**

### CODE REVIEW

**Comment by yvoitenko** [comment]
### !Notice

In order to meet the requirement of #485 I have replaced the log file name with the `CONTAINER_ROLE`. So that now two log files will be created: `app.log` and `queue.log` - for app and queue containers respectively. The previous log from `laravel.log` will not be displayed in the `App Logs` screen, only the newly created logs will.

**Review by cesdias — CHANGES_REQUESTED** [review]
ILP Packets aren't displayed correctly in the log window (Message Log menu).

image

**Comment by yvoitenko** [comment]
> ILP Packets aren't displayed correctly in the log window (Message Log menu).
> 
> image

Hi @cesdias ! I have updated the PR with fixes, please re-check. Thanks

**Comment by cesdias** [comment]
Hello @yvoitenko thanks for the fixes.

I am still getting the log out of the window when you click "Request" button through "Test Steps" inside the session.

image

image

**Comment by yvoitenko** [comment]
> Hello @yvoitenko thanks for the fixes.
> 
> I am still getting the log out of the window when you click "Request" button through "Test Steps" inside the session.
> 
> image
> 
> image

That's very strange, because I don't
image

**Review by cesdias — APPROVED** [review]
Need to check for the ILP Packet content showed out of bounds in the log window in very specific situations.

**Pull request merged**
